### ISSUE TITLE
After editing with Aviary, shows incorrect photo

### ISSUE THREAD

**Issue by joewalnes** [novaphotos/nova-ios-app#12]
## Steps to reproduce
-    Take a photo
-    Edit in Aviary
-    Make some obvious tweaks
-    Hit "Done" in Aviary
## Expected result

Should return to photo viewer, showing edited photo
## Actual result

Shows an entirely different photo (not even the original)

**Comment by joewalnes** [comment]
If this help - the incorrect photo it always ends up showing for me is my last photo in my last album (even though I may be looking at another album).

**Comment by pix0r** [comment]
This is going to require some more architectural changes to the `ALAssetsLibrary` code (specifically `SSChronologicalAssetsLibraryService`).  The current mechanism attempts to track `ALAsset` URL's across `ALAssetsLibrary` changes to determine which items have been added, removed or changed.  It turns out this is brittle when using albums (which I hadn't tested with).

**Comment by pix0r** [comment]
This has been slightly improved by the previously mentioned commit (a8a3ee6) but still requires work.  Currently the correct photo is displayed but we lose track of the asset library, so navigation between photos breaks after editing a photo. (commit a8a3ee6 does not address the `SSChronologicalAssetsLibraryService` changes; it only improves tracking the "active" photo in `SSLibraryViewController`.)
